language: node_js
node_js:
    - "8"
dist: trusty
services:
    - mongodb
    - redis-server
env:
    - NODE_ENV=ci PORT=3000
cache:
    directories:
        - advancedStarter/node_modules
        - advancedStarter/client/node_modules
install:
    - npm install --prefix advancedStarter
    - npm run build --prefix advancedStarter
script:
    - nohup npm run start --prefix advancedStarter &
    - sleep 3
    - npm run test --prefix advancedStarter